- Books.mediawiki
As per [Erik Yuzwa's request](https://github.com/libsdl-org/sdlwiki/issues/13#issue-847683808), I removed target="blank" from the titles of his books and added the clarification that they are on SDL 1.2 material.
> Books.mediawiki: Remove target="blank" from titles + small fixes

- SDL_HINT_MOUSE_RELATIVE_SCALING.mediawiki
- SDL_RenderSetLogicalSize.mediawiki
This change adds two things:
- A page for the ``SDL_HINT_MOUSE_RELATIVE_SCALING`` hint.
- A link to said page from the ``SDL_RenderSetLogicalSize()`` page.
I did these both manually, as ``wikiheaders.pl`` doesn't handle #defines and enums yet, and I couldn't quite find a way of creating a new page from the ``ghwikipp`` interface.
> Add some documentation for SDL_HINT_MOUSE_RELATIVE_SCALING

- SDL_CreateMutex.mediawiki
- SDL_CreateThread.mediawiki
- SDL_GetThreadID.mediawiki
- SDL_TryLockMutex.mediawiki
- SDL_WaitThread.mediawiki
Edits of:
- https://wiki.libsdl.org/SDL_TryLockMutex
- https://wiki.libsdl.org/SDL_CreateMutex
- https://wiki.libsdl.org/SDL_WaitThread
- https://wiki.libsdl.org/SDL_GetThreadID
- https://wiki.libsdl.org/SDL_CreateThread
This PR brings a few minor corrections to threading code examples:
- all occurrences of `(f)printf` have been replaced by `SDL_Log(Error)`.
- removed `sdtio.h` if it was no longer necessary to the example.
- corrected syntax highlighting to be `c` instead of `c++`.
> Threading: Replaced printf in code examples.

- SDL_SemWait.mediawiki
Edit of: https://wiki.libsdl.org/SDL_SemWait
This includes the fixes requested in #196.
This examples consists in:
- A single thread calling post on the semaphore every 2 seconds.
- Ten threads, each calling `SDL_SemWait` on the semaphore.
- Describing how to handle the return value of `SDL_SemWait`.
> SDL_SemWait: Added code example.

- SDL_LockMutex.mediawiki
Edit of: https://wiki.libsdl.org/SDL_LockMutex
This includes the fixes requested in #195.
The example consists in:
- Locking with `SDL_LockMutex`.
- Describing how to handle the return value.
> SDL_LockMutex: Added code example.

- SDL_GetVersion.mediawiki
Edit of: https://wiki.libsdl.org/SDL_GetVersion
This PR brings the following fixes to the code example:
- Replace `printf` with `SDL_Log`.
- Replace `%d` with `%u` as the SDL_version structure stores unsigned ints.
- Set syntax highlighting to `c` instead of `c++`.
> SDL_GetVersion: update code example.

- SDL_VERSION.mediawiki
- SDL_version.mediawiki
Edits of:
- https://wiki.libsdl.org/SDL_VERSION
- https://wiki.libsdl.org/SDL_version
This PR replaces the `Include(SDL_GetVersion...)` statements in both pages with a copy of the updated example proposed in #200.
> SDL_version/VERSION: Added code example.

- CategoryTimer.mediawiki
This edit adds a link to [SDL_GetTicks64](https://wiki.libsdl.org/SDL_GetTicks64) on the [Timer Category](https://wiki.libsdl.org/CategoryTimer) page.
> CategoryTimer: Added link to GetTicks64 on Timer page.

- SDL_GetTicks64.mediawiki
This PR aims to bring the same changes as #207.
The bot reverted the changes presumably because the `SDL_GetTicks64` page lacked `CategoryTimer` at the bottom.
Apologies for the redundancy with the previous PR.
> SDL_GetTicks64: Add timer category.

- SDL_MouseWheelEvent.mediawiki
The header documents these fields, but the wiki does not. This change simply copies the definitions from the header into the wiki.
https://github.com/libsdl-org/SDL/blob/120c76c84bbce4c1bfed4e9eb74e10678bd83120/include/SDL_events.h#L304
> SDL_MouseWheelEvent: Document preciseX and preciseY

- SDL2/CategoryMessageBox.mediawiki
Fixes typo causing broken link
> SDL2/CategoryMessageBox: fix typo

- SDL2/SDL_GetBasePath.md
- SDL2/SDL_GetPrefPath.md
- SDL3/SDL_GetBasePath.md
- SDL3/SDL_GetPrefPath.md
The backslashes were escaping the following ' character instead of being displayed.
> Fix Windows path separators.

- SDL2/SDL_SysWMinfo.mediawiki
These used deprecated and unsupported HTML elements, and it made the wiki page look like a mess, so I tried to update it.
> Attempt to fix styles on SDL_SysWMinfo page

- SDL3/SDL_DialogFileCallback.md
- SDL3/SDL_DialogFileFilter.md
Replaces https://github.com/libsdl-org/SDL/pull/9729, the same description applies.
This is my first PR here, please let me know if I got something wrong!
> Add example code for dialog filter and callback

- SDL3/SDL_DialogFileCallback.md
- SDL3/SDL_DialogFileFilter.md
Some examples were outdated; I've updated them to follow the latest API changes. Specifically, the array of filters is no longer `NULL`-terminated, and the filter argument of the callback no longer distinguishes "No filter selected" and "Fetching selected filter is unsupported".
> Update SDL3/SDL_DialogFile* examples

- SDL3/SDL_Vulkan_GetInstanceExtensions.md
Fix a bug from the C++ to C conversion in cb047371215fed1ccfb68721218522cfda68ce85
> Fix SDL_Vulkan_GetInstanceExtensions example

- SDL3/FAQUsingSDL.md
A period that looks like it should have been a comma.
> Fix typo in FAQUsingSDL.md

- SDL3/SDL_EVENT_PEN_AXIS.md
- SDL3/SDL_EVENT_PEN_BUTTON_DOWN.md
- SDL3/SDL_EVENT_PEN_BUTTON_UP.md
- SDL3/SDL_EVENT_PEN_DOWN.md
- SDL3/SDL_EVENT_PEN_MOTION.md
- SDL3/SDL_EVENT_PEN_PROXIMITY_IN.md
- SDL3/SDL_EVENT_PEN_PROXIMITY_OUT.md
- SDL3/SDL_EVENT_PEN_UP.md
- SDL3/SDL_PenAxisEvent.md
- SDL3/SDL_PenButtonEvent.md
- SDL3/SDL_PenMotionEvent.md
- SDL3/SDL_PenProximityEvent.md
- SDL3/SDL_PenTouchEvent.md
Adds https://wiki.libsdl.org/SDL3/CategoryPen to pen related structs and enum members defined in `SDL_events.h`
> Add [CategoryPen] to pen related events

- SDL3/SDL_CreateTray.md
This adds a very basic example program to give a quick start for developers wanting to use trays.
Closes https://github.com/libsdl-org/SDL/issues/12214
Some things to check before merging:
- I haven't put all the error checking that I've done for `testtray` because I wanted to go for maximum simplicity; should I add some error checking?
- I've only added the example in `SDL_CreateTray` because I felt that was the most natural entry point to trays; should I add a note in the documentation of other functions to redirect people to SDL_CreateTray for some example code?
- Should I add the "See also" links of the functions I used in the SDL_CreateTray page?
> Add code examples for SDL_CreateTray

- SDL3/Tutorials/FrontPage.md
Noticed this during my previous PR, which modifies the same file, but didn't want to clutter that with an unrelated change.
> Fix formatting of a link on the Tutorials page

- SDL3/FrontPage.md
These were things I was looking for a couple of times, and couldn't easily find in the place I expected it, which was this list. They are linked from the Tutorials page, which is also a good place for them to be linked. I feel having them linked in both places is the best. That doubles the chances of people seeing them!
I got the description text from the Tutorials page.
> Added links to the Examples and Demos onto the FrontPage.md
